Update deploymen-pipeline.yaml

diff --git a/.github/workflows/deploymen-pipeline.yaml b/.github/workflows/deploymen-pipeline.yaml
--- a/.github/workflows/deploymen-pipeline.yaml
+++ b/.github/workflows/deploymen-pipeline.yaml
@@ -7,14 +7,37 @@ on:
         description: 'Release version (e.g., v1.0.0)'
         required: true
         type: string
+      action:
+        description: 'Select action (build, deploy, both)'
+        required: true
+        type: choice
+        options:
+          - build
+          - deploy
+          - both
 
 env:
   REGISTRY: docker.io
   IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
   
 jobs:
+  validate-version-format:
+    name: Validate version format
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Validate version format
+        run: |
+          if [[ ! "${{ github.event.inputs.release_version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Invalid version format. Use semantic versioning (e.g., v1.0.0)"
+            exit 1
+          fi
+          
   build-and-push-image:
     name: Build and Push Docker Image & Create Git Tag
+    needs: validate-version-format
     runs-on: ubuntu-latest
     permissions:
       contents: write  # Critical fix for tag pushing
@@ -23,13 +46,6 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0 # # Required to access all tags
-
-      - name: Validate version format
-        run: |
-          if [[ ! "${{ github.event.inputs.release_version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Invalid version format. Use semantic versioning (e.g., v1.0.0)"
-            exit 1
-          fi
           
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -47,6 +63,7 @@ jobs:
             ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.release_version }}
 
       - name: Create Git tag
+        if: success()
         run: |
           TAG=${{ github.event.inputs.release_version }}
           
